version: "3.8"

services:
  owan:
    restart: always
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    env_file:
      - owan.env
    build:
      context: ../../
      dockerfile: environments/development/Dockerfile
    tty: true
    ports:
      - "8000:8000"
    volumes:
      - ../../../owan:/home/gatheluck/owan
    links:
      - redis

  redis:
    image: redis:6.0-alpine
    restart: always
