version: "3.8"

services:
  owan-broker:
    container_name: owan-broker
    restart: always
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    build:
      context: ../../
      dockerfile: environments/jetson/Dockerfile
    links:
      - redis
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    command: poetry run gunicorn 'owan.wsgi:main()' -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8000 --log-level debug
    expose:
      - 8000

  owan-worker:
    container_name: owan-worker
    restart: always
    build:
      context: ../../
      dockerfile: environments/jetson/Dockerfile
    links:
      - redis
    command: poetry run celery --app owan.worker worker --pool solo --concurrency 1

  redis:
    container_name: redis
    image: redis:6.0-alpine
    restart: always
